// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDebSaEdvYW8L8vdqxoLsX8AphWgaIp230',
    appId: '1:57770731921:web:925a57c78dbe6e7f851230',
    messagingSenderId: '57770731921',
    projectId: 'decentrathonnotifications',
    authDomain: 'decentrathonnotifications.firebaseapp.com',
    storageBucket: 'decentrathonnotifications.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnGNCiABCxh8zV8qus7sYYoaw6VxJgY_Y',
    appId: '1:57770731921:android:f677edee4f4792e1851230',
    messagingSenderId: '57770731921',
    projectId: 'decentrathonnotifications',
    storageBucket: 'decentrathonnotifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDanpGrar0ddBDdmw_L6XOXSgTPfdlrK5k',
    appId: '1:57770731921:ios:7917813c6fcf073e851230',
    messagingSenderId: '57770731921',
    projectId: 'decentrathonnotifications',
    storageBucket: 'decentrathonnotifications.firebasestorage.app',
    iosBundleId: 'com.example.decentrathonNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDanpGrar0ddBDdmw_L6XOXSgTPfdlrK5k',
    appId: '1:57770731921:ios:7917813c6fcf073e851230',
    messagingSenderId: '57770731921',
    projectId: 'decentrathonnotifications',
    storageBucket: 'decentrathonnotifications.firebasestorage.app',
    iosBundleId: 'com.example.decentrathonNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDebSaEdvYW8L8vdqxoLsX8AphWgaIp230',
    appId: '1:57770731921:web:cbcef8baa2b30a9f851230',
    messagingSenderId: '57770731921',
    projectId: 'decentrathonnotifications',
    authDomain: 'decentrathonnotifications.firebaseapp.com',
    storageBucket: 'decentrathonnotifications.firebasestorage.app',
  );
}
